name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions for Deployment 🚀
on:
  push:
    branches:
      - main
env:
  SERVER: gh-pages
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository code
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name zflegle3
          git config --global user.email zflegle3@gmail.com

      # Install dependencies with --legacy-peer-deps flag
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Deploy to GitHub Pages using the gh-pages package
      - name: Deploy App
        run: npm run deploy
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          REACT_APP_GOOGLE_MAPS_API: ${{ secrets.REACT_APP_GOOGLE_MAPS_API }} 
          github_token: ${{ secrets.GITHUB_TOKEN }}
