name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions for Deployment 🚀
on:
  push:
    branches:
      - main
env:
  SERVER: gh-pages
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository code
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name zflegle3
          git config --global user.email zflegle3@gmail.com
          git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com".insteadOf "https://github.com"

      # Install dependencies with --legacy-peer-deps flag
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Build App
      - name: Build App
        run: npm run build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          REACT_APP_GOOGLE_MAPS_API: ${{ secrets.REACT_APP_GOOGLE_MAPS_API }} 

       # Deploy to GitHub Pages using the gh-pages package
      # - name: Deploy to GitHub Pages
      #   run: npm run deploy
      #   env:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
