name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions for Deployment 🚀
on:
  push:
    branches:
      - main
env:
  SERVER: gh-pages
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository code
      - name: Check out repository code
        uses: actions/checkout@v4

      # Install dependencies with --legacy-peer-deps flag
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Build the React app
      - name: Build the React app
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}  # Add any other environment variables you need
        run: npm run build

      # Deploy to GitHub Pages using the gh-pages package
      - name: Deploy to GitHub Pages
        run: npm run deploy
